FROM node:20-bullseye-slim

WORKDIR /backend

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
COPY tsconfig.build.json tsconfig.json ./
COPY src ./src

RUN npx prisma generate
RUN npm run build

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3001

COPY entrypoint.sh ./
COPY migrate-uploads-to-r2.mjs ./
RUN chmod +x entrypoint.sh

EXPOSE 3001

CMD ["./entrypoint.sh"]
